## InfraSonar docker-compose.yml file
##
## Set the correct TOKEN variables before starting.

x-infrasonar-template: &infrasonar
  network_mode: host
  restart: always
  logging:
    options:
      max-size: 5m
  volumes:
      - ./data:/data/
  labels:
    com.centurylinklabs.watchtower.enable: TRUE

services:
  agentcore:
    << : *infrasonar
    image: ghcr.io/infrasonar/agentcore
    environment:
      TOKEN: ${AGENTCORE_TOKEN}
  docker-agent:
    << : *infrasonar
    image: ghcr.io/infrasonar/docker-agent
    environment:
      TOKEN: ${AGENT_TOKEN}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/data/
  # Auto Update service
  watchtower:
    image: containrrr/watchtower
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro
    environment:
      WATCHTOWER_CLEANUP: TRUE
      WATCHTOWER_INCLUDE_RESTARTING: TRUE
      WATCHTOWER_POLL_INTERVAL: 21600
      WATCHTOWER_LABEL_ENABLE: TRUE
  # InfraSonar probes
  dns-probe:
    << : *infrasonar
    image: ghcr.io/infrasonar/dns-probe
  eaton-probe:
    << : *infrasonar
    image: ghcr.io/infrasonar/eaton-probe
  esx-probe:
    << : *infrasonar
    image: ghcr.io/infrasonar/esx-probe
  hpilo-probe:
    << : *infrasonar
    image: ghcr.io/infrasonar/hpilo-probe
  hpprocurve-probe:
    << : *infrasonar
    image: ghcr.io/infrasonar/hpprocurve-probe
  http-probe:
    << : *infrasonar
    image: ghcr.io/infrasonar/http-probe
  mssql-probe:
    << : *infrasonar
    image: ghcr.io/infrasonar/mssql-probe
  netapp-probe:
    << : *infrasonar
    image: ghcr.io/infrasonar/netapp-probe
  paloalto-probe:
    << : *infrasonar
    image: ghcr.io/infrasonar/paloalto-probe:unstable
  ping-probe:
    << : *infrasonar
    image: ghcr.io/infrasonar/ping-probe
  snmp-probe:
    << : *infrasonar
    image: ghcr.io/infrasonar/snmp-probe
  santricity-probe:
    << : *infrasonar
    image: ghcr.io/infrasonar/santricity-probe
  synology-probe:
    << : *infrasonar
    image: ghcr.io/infrasonar/synology-probe
  tcp-probe:
    << : *infrasonar
    image: ghcr.io/infrasonar/tcp-probe
  unifi-probe:
    << : *infrasonar
    image: ghcr.io/infrasonar/unifi-probe
  vcenter-probe:
    << : *infrasonar
    image: ghcr.io/infrasonar/vcenter-probe
  wmi-probe:
    << : *infrasonar
    image: ghcr.io/infrasonar/wmi-probe