# Project information
site_name: InfraSonar

# Copyright
copyright: "Copyright &copy; 2023 Cesbit"

# Google analytics (Uses Cesbit Google account)
extra:
  analytics:
    provider: google
    property: G-N3NW18WYVM

# Theme configuration
theme:
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  name: material
  custom_dir: theme
  favicon: images/favicon.ico
  logo: images/infrasonar_logo.png
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.indexes
    # Enables the Code copy button
    - content.code.copy

# Custom styling
extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - attr_list
  - admonition
  - def_list
  - md_in_html
  - footnotes
  - pymdownx.highlight
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.keys
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tasklist:
      custom_checkbox: true

# Page tree
nav:
  - Home: index.md
  - Documentation:
    - Introduction:
       - Getting started: introduction/getting_started.md
       - Platform: introduction/platform.md
       - Support: introduction/support.md
       - Terminology: introduction/terminology.md
       - About InfraSonar: introduction/about.md
    - Guides:
       - Raspberry Pi dashboard: guides/raspberrypi_dashboard.md
       - Migration: guides/migration.md
       - Remote support: guides/remote_support.md
    - Privacy & Security:
       - Security: privacy-security/security_considerations.md
       - Privacy: privacy-security/privacy.md
  - Application:
    - application/index.md
    - Profile menu:
       - Profile: application/profile.md
    - Main menu:
       - Home: application/home.md
       - Dashboard: application/dashboard.md
       - Containers: application/containers.md
    - Container:
      - Alerts: application/alerts.md
      - Assets: application/assets.md
      - Child containers: application/child_containers.md
      - Conditions: application/conditions.md
      - Labels: application/labels.md
      - Schedule: application/schedule.md
      - Views: application/views.md
      - Credits: application/credits.md
      - Rules: application/rules.md
      - Agentcores: application/agentcores.md
      - Zones: application/zones.md
      - Users: application/users.md
      - Webhooks: application/webhooks.md
      - Tokens: application/tokens.md
      - Time series: application/timeseries.md
      - Collectors: application/collectors.md
      - Reporting: application/reporting.md
      - Log: application/log.md
      - Trash: application/trash.md
  - Collectors:
    - collectors/index.md
    - Agents:
        - collectors/agents/index.md
        -  Docker: collectors/agents/docker.md
        -  Kubernetes: collectors/agents/kubernetes.md
        -  Windows: collectors/agents/windows.md
        -  Speedtest: collectors/agents/speedtest.md
    - Probes:
        - collectors/probes/index.md
        - Appliance:
            - collectors/probes/appliance/index.md
            - Ubuntu guide: collectors/probes/appliance/ubuntu_installation.md
            - Windows guide: collectors/probes/appliance/windows_installation.md
            - InfraSonar appliance (OVA): collectors/probes/appliance/appliance_installation.md
            - InfraSonar Manager: collectors/probes/appliance/appliance_manager.md
            - Nano basics: collectors/probes/appliance/nano_basics.md
            - Credentials: collectors/probes/appliance/credentials.md
            - Advanced: collectors/probes/appliance/advanced.md
        - Agentcore: collectors/probes/agentcore.md
        - DNS: collectors/probes/dns.md
        - HTTP: collectors/probes/http.md
        - Microsoft WMI:
            - collectors/probes/wmi/index.md
            - EventLog: collectors/probes/wmi/eventlog.md
            - Hyper-V: collectors/probes/wmi/hyperv.md
            - Hyper-V guest: collectors/probes/wmi/hypervguest.md
        - Microsoft SQL Server: collectors/probes/mssql.md
        - MySQL Server: collectors/probes/mysql.md
        - NetApp: collectors/probes/netapp.md
        - Palo Alto: collectors/probes/paloalto.md
        - Ping: collectors/probes/ping.md
        - SANtricity / NetApp E-Series: collectors/probes/santricity.md
        - SNMP:
            - collectors/probes/snmp/index.md
            - APC UPS: collectors/probes/snmp/apcups.md
            - Dell iDRAC: collectors/probes/snmp/idrac.md
            - EATON: collectors/probes/snmp/eaton.md
            - HP ILO: collectors/probes/snmp/hpilo.md
            - HP ProCurve: collectors/probes/snmp/hpprocurve.md
            - Synology: collectors/probes/snmp/synology.md
            - UniFi: collectors/probes/snmp/unifi.md
        - TCP: collectors/probes/tcp.md
        - UniFi: collectors/probes/unificontroller.md
        - VMWare:
            - collectors/probes/vmware/index.md
            - ESXi: collectors/probes/vmware/esx.md
            - vCenter: collectors/probes/vmware/vcenter.md
            - VMware guest: collectors/probes/vmware/vmwareguest.md
    - Services:
        - collectors/services/index.md
        - Last seen: collectors/services/last_seen.md
        - MailRoundTrip: collectors/services/mailroundtrip.md
        - Microsoft 365: collectors/services/microsoft_365.md
        - Microsoft Azure: collectors/services/microsoft_azure.md
        - Palo Alto: collectors/services/paloalto.md
        - Ping: collectors/services/ping.md
  - Integrations:
      - Overview: integrations/index.md
      - ConnectWise Manage: integrations/connectwise_manage.md
  - API reference:
      - Overview: api/overview.md
      - Authentication: api/authentication.md
      - ID's: api/ids.md
      - Asset:
        - Query asset: api/asset/query.md
        - Query asset alerts: api/asset/query-alerts.md
        - Query asset Id: api/asset/query-id.md
        - Query check data: api/asset/query-check-data.md
        - Query forecast data: api/asset/query-forecast-data.md
        - Query time series: api/asset/query-time-series.md
        - Insert check data: api/asset/insert-check-data.md
        - Set asset description: api/asset/set-description.md
        - Set asset kind: api/asset/set-kind.md
        - Set asset mode: api/asset/set-mode.md
        - Set asset name: api/asset/set-name.md
        - Add label to asset: api/asset/add-label.md
        - Purge notifications: api/asset/purge-notifications.md
        - Enable check: api/asset/enable-check.md
        - Disable check: api/asset/disable-check.md
        - Remove collector from asset: api/asset/remove-collector.md
        - Remove label from asset: api/asset/remove-label.md
        - Upsert collector to asset: api/asset/upsert-collector.md
      - Alert:
        - Query alert: api/alert/query.md
        - Add message to alert: api/alert/message.md
        - Assign alert: api/alert/assign.md
        - Close alert: api/alert/close.md
      - Container:
        - Create asset: api/container/create-asset.md
        - Query container: api/container/query.md
        - Query container Id: api/container/query-id.md
        - Query container alerts: api/container/query-alerts.md
        - Query container assets: api/container/query-assets.md
        - Query container collectors: api/container/query-collectors.md
        - Set container mode: api/container/set-mode.md
        - Purge notifications: api/container/purge-notifications.md
        - Purge time-series: api/container/purge-time-series.md
      - Label:
        - Query label: api/label/query.md
      - Reporting:
        - Query reporting: api/reporting/query.md
        - Get report: api/reporting/get-report.md