# Project information
site_name: InfraSonar



# Copyright
copyright: "Copyright &copy; 2022 Cesbit"

# Theme configuration
theme:
  name: material
  custom_dir: theme
  favicon: images/favicon.ico
  logo: images/infrasonar_logo.png
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.indexes

# Custom styling
extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - attr_list
  - admonition
  - def_list
  - md_in_html
  - pymdownx.highlight
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.keys
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tasklist:
      custom_checkbox: true

# Page tree
nav:
  - Home: index.md
  - Documentation:
      - Introduction:
          - Getting started: documentation/introduction/getting_started.md
          - What is InfraSonar: documentation/introduction/what_is_Infra_Sonar.md
          - Platform: documentation/introduction/platform.md
          - Contact us: documentation/introduction/contact_us.md
      - Collectors:
          - Agents:
              - documentation/collectors/agents/index.md
              -  Docker: documentation/collectors/agents/docker.md
          - Probes:
              - documentation/collectors/probes/index.md
              - Appliance:
                  - Deployment: documentation/collectors/probes/appliance/appliance_deployment.md
                  - Credentials: documentation/collectors/probes/appliance/credentials.md
                  - Agent-core: documentation/collectors/probes/agentcore.md
              - DNS: documentation/collectors/probes/dns.md
              - HTTP: documentation/collectors/probes/http.md
              - Microsoft Azure: documentation/collectors/probes/microsoft_azure.md
              - Microsoft WMI: documentation/collectors/probes/wmi.md
              - Microsoft SQL Server: documentation/collectors/probes/microsoft_sql.md
              - NetApp: documentation/collectors/probes/netapp.md
              - Ping: documentation/collectors/probes/ping.md
              - Pure storage: documentation/collectors/probes/pure_probe.md
              - SNMP: documentation/collectors/probes/snmp.md
              - TCP: documentation/collectors/probes/tcp.md
              - VMware: documentation/collectors/probes/vmware.md
              - SMTP: documentation/collectors/probes/smtp.md
      - Web application:
          - Environments: documentation/web_application/environment.md
          - Hosts: documentation/web_application/assets.md
          - Labels: documentation/web_application/labels.md
          - Conditions: documentation/web_application/conditions.md
          - Subscriptions: documentation/web_application/subscriptions.md
          - Tasks: documentation/web_application/tasks.md
          - User management: documentation/web_application/user_management.md
      - Guides:
          - Migration: documentation/guides/migration.md
          - Remote support: documentation/guides/remote_support.md
      - Privacy & Security:
          - Security: documentation/privacy-security/security_considerations.md
          - Privacy: documentation/privacy-security/privacy.md
  - Integrations:
      - Overview: integrations/index.md
      - DutyCalls:
        - Getting started: integrations/dutycalls/dutycalls-getting-started.md
        - Best practices: integrations/dutycalls/dutycalls-best-practices.md
      - ConnectWise Manage: integrations/connectwise_manage.md
  - API reference:
      - Overview: api/overview.md
      - Authentication: api/authentication.md
      - UUID: api/uuid.md
      - Keystrings: api/keystring.md
      - Asset:
        - Query asset: api/asset/query.md
        - Query asset alerts: api/asset/query-alerts.md
        - Query asset Id: api/asset/query-id.md
        - Insert check data: api/asset/insert-check-data.md
        - Add label to asset: api/asset/add-label.md
        - Remove collector from asset: api/asset/remove-collector.md
        - Remove label from asset: api/asset/remove-label.md
        - Set asset kind: api/asset/set-kind.md
        - Set asset mode: api/asset/set-mode.md
        - Upsert collector to asset: api/asset/upsert-collector.md
      - Alert:
        - Query alert: api/alert/query.md
      - Container:
        - Create asset: api/container/create-asset.md
        - Query container: api/container/query.md
        - Query container Id: api/container/query-id.md
        - Query container alerts: api/container/query-alerts.md
        - Query container assets: api/container/query-assets.md
        - Set container mode: api/container/set-mode.md
        - Purge notifications: api/container/purge-notifications.md
        - Purge time-series: api/container/purge-time-series.md
      - ConnectWise Manage add-on:
        - Set CWM: api/cwm/set-cwm.md
      - Examples:
          - Powershell: api/examples/powershell.md


  - Changelog: changelog.md
