## InfraSonar docker-compose.yml file
##
## Set the correct TOKEN variables in the .env file before starting.

x-infrasonar-template: &infrasonar
  network_mode: host
  restart: always
  logging:
    options:
      max-size: 5m
  volumes:
    - ./data:/data/
  labels:
    ## We opt to only update our own containers using the AGENTCORE token to identiy the scope
    com.centurylinklabs.watchtower.scope: ${AGENTCORE_TOKEN}

services:
  ## Auto Update service
  watchtower:
    << : *infrasonar
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro
    environment:
      WATCHTOWER_CLEANUP: TRUE
      WATCHTOWER_INCLUDE_RESTARTING: TRUE
      ## We update every 6 hours
      WATCHTOWER_POLL_INTERVAL: 21600
      ## Identies the scope for updating
      WATCHTOWER_SCOPE: ${AGENTCORE_TOKEN}
  ## InfraSonar agents
  docker-agent:
    << : *infrasonar
    image: ghcr.io/infrasonar/docker-agent
    environment:
      TOKEN: ${AGENT_TOKEN}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/data/
  # If you want the Speedtest probe, make sure to add this probe the asset is
  # created
  #   speedtest-agent:
  #      << : *infrasonar
  #      image: ghcr.io/infrasonar/speedtest-agent
  #      environment:
  #        TOKEN: ${AGENT_TOKEN}

  ## InfraSonar probes
  agentcore:
    << : *infrasonar
    image: ghcr.io/infrasonar/agentcore
    environment:
      TOKEN: ${AGENTCORE_TOKEN}
      AGENTCORE_ZONE: ${AGENTCORE_ZONE_ID}
  dns-probe:
    << : *infrasonar
    image: ghcr.io/infrasonar/dns-probe
  eaton-probe:
    << : *infrasonar
    image: ghcr.io/infrasonar/eaton-probe
  esx-probe:
    << : *infrasonar
    image: ghcr.io/infrasonar/esx-probe
  hpilo-probe:
    << : *infrasonar
    image: ghcr.io/infrasonar/hpilo-probe
  hpprocurve-probe:
    << : *infrasonar
    image: ghcr.io/infrasonar/hpprocurve-probe
  http-probe:
    << : *infrasonar
    image: ghcr.io/infrasonar/http-probe
  mssql-probe:
    << : *infrasonar
    image: ghcr.io/infrasonar/mssql-probe
  mysql-probe:
    << : *infrasonar
    image: ghcr.io/infrasonar/mysql-probe
  netapp-probe:
    << : *infrasonar
    image: ghcr.io/infrasonar/netapp-probe
  paloalto-probe:
    << : *infrasonar
    image: ghcr.io/infrasonar/paloalto-probe
  ping-probe:
    << : *infrasonar
    image: ghcr.io/infrasonar/ping-probe
  snmp-probe:
    << : *infrasonar
    image: ghcr.io/infrasonar/snmp-probe
  santricity-probe:
    << : *infrasonar
    image: ghcr.io/infrasonar/santricity-probe
  synology-probe:
    << : *infrasonar
    image: ghcr.io/infrasonar/synology-probe
  tcp-probe:
    << : *infrasonar
    image: ghcr.io/infrasonar/tcp-probe
  unifi-probe:
    << : *infrasonar
    image: ghcr.io/infrasonar/unifi-probe
  vcenter-probe:
    << : *infrasonar
    image: ghcr.io/infrasonar/vcenter-probe
  wmi-probe:
    << : *infrasonar
    image: ghcr.io/infrasonar/wmi-probe
