apiVersion: v1
kind: Service
metadata:
  labels:
    app: agentcore
  name: agentcore
  namespace: monitoring
spec:
  clusterIP: None
  publishNotReadyAddresses: false
  ports:
  - name: probe
    port: 8750
  selector:
    app: agentcore
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: agentcore
  namespace: monitoring
  labels:
    app: agentcore
spec:
  selector:
    matchLabels:
      app: agentcore
  serviceName: agentcore
  replicas: 1
  template:
    metadata:
      labels:
        app: agentcore
    spec:
      dnsConfig:
        searches:
        - agentcore.monitoring.svc.cluster.local
      containers:
      - name: agentcore
        image: ghcr.io/infrasonar/agentcore:latest
        imagePullPolicy: Always
        env:
        - name: AGENTCORE_NAME
          value: "agentcore"
        - name: TOKEN
          value: "<REPLACE_WITH_TOKEN>"
        - name: AGENTCORE_ZONE
          value: "0"
        - name: AGENTCORE_DATA
          value: "/data"
        volumeMounts:
        - name: data
          mountPath: /data
        ports:
        - name: probe
          containerPort: 8750
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 5Gi
